name: Push application to ECR

on:
  push:
    branches:
      - main-disable
jobs:
  deploy:
      if: github.ref == 'refs/heads/main'
      name: Deploy to dev print-ip
      runs-on: ubuntu-latest
      environment: development

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secret.aws-access-key-id}}
            aws-secret-access-key: ${{ secret.aws-secret-access-key}}
            aws-region: us-west-2

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build, tag, and push image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: deel-print-ip
            IMAGE_TAG: latest
          run: |
            # Build a docker container and  push it to ECR so that it can be deployed to ECS.
            docker build --platform linux/amd64 -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"